# configs/compressor/gcc.yaml

# Hydra가 이 파일을 읽어 어떤 파이썬 클래스를 객체로 만들지 지정합니다.
_target_: utils.data.coil_compression.GCCCompressor

# GCCCompressor.__init__에 전달될 파라미터
target_coils: auto
# target_coils: 4
num_calib_lines: 24
sliding_window_size: 5
use_aligned_gcc: true


